name: Build, Release and Javadoc
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: fregante/setup-git-user@v1
    - name: Compile
      run: |
        mvn compile
    - name: Maven Release
      run: |
        mvn release:prepare release:perform
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Javadoc
      run: |
        mvn javadoc:javadoc
        mkdir pages
        cd pages
        mkdir docs
        cd ..
        mv target/site/apidocs/* ./pages/docs
    - name: Put Javadoc on gh-pages branch
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
